// ============================================================
//  ShopNest — Real Products Data (India, 2026)
//  Genuine brands · Accurate prices · Real descriptions
// ============================================================

const productsData = [

  // ── ELECTRONICS ─────────────────────────────────────────
  {
    id: 1,
    name: "boAt Airdopes 141 TWS Earbuds",
    brand: "boAt",
    price: 1299,
    originalPrice: 2990,
    category: "electronics",
    rating: 4.4,
    reviews: 1284500,
    emoji: "🎧",
    description: "42H total playback, ENx™ noise cancellation mic, IPX4 water-resistant, instant voice assistant support.",
    badge: "Best Seller",
    inStock: true
  },
  {
    id: 2,
    name: "Redmi 13C 5G (6GB + 128GB)",
    brand: "Xiaomi",
    price: 11999,
    originalPrice: 13999,
    category: "electronics",
    rating: 4.3,
    reviews: 87600,
    emoji: "📱",
    description: "MediaTek Dimensity 6100+ 5G, 50MP AI triple camera, 5000mAh battery, 90Hz display.",
    badge: "New",
    inStock: true
  },
  {
    id: 3,
    name: "Fire-Boltt Ninja Call Pro Smartwatch",
    brand: "Fire-Boltt",
    price: 1799,
    originalPrice: 4999,
    category: "electronics",
    rating: 4.2,
    reviews: 312000,
    emoji: "⌚",
    description: "Bluetooth calling, 1.83\" HD display, SpO2 & heart rate monitor, 100+ sports modes, 7-day battery.",
    badge: "Hot Deal",
    inStock: true
  },
  {
    id: 4,
    name: "Logitech MK215 Wireless Keyboard & Mouse",
    brand: "Logitech",
    price: 1595,
    originalPrice: 2295,
    category: "electronics",
    rating: 4.4,
    reviews: 54800,
    emoji: "⌨️",
    description: "2.4GHz wireless, 2-year battery life on keyboard, spill-resistant design, Plug-and-play USB receiver.",
    badge: "",
    inStock: true
  },
  {
    id: 5,
    name: "JBL Go 3 Portable Bluetooth Speaker",
    brand: "JBL",
    price: 2499,
    originalPrice: 3499,
    category: "electronics",
    rating: 4.5,
    reviews: 96400,
    emoji: "🔊",
    description: "IP67 waterproof & dustproof, 5 hours playtime, USB-C charging, bold JBL Pro Sound.",
    badge: "Top Rated",
    inStock: true
  },
  {
    id: 6,
    name: "Mi 80cm (32\") Smart TV 4A",
    brand: "Xiaomi",
    price: 17499,
    originalPrice: 21999,
    category: "electronics",
    rating: 4.3,
    reviews: 223000,
    emoji: "📺",
    description: "Android TV 11, 20W stereo speakers, Dolby Audio, 1GB RAM + 8GB storage, Google Assistant built-in.",
    badge: "",
    inStock: true
  },

  // ── FASHION ─────────────────────────────────────────────
  {
    id: 7,
    name: "US POLO ASSN. Men's Polo T-Shirt",
    brand: "US Polo Assn.",
    price: 699,
    originalPrice: 1299,
    category: "fashion",
    rating: 4.3,
    reviews: 43700,
    emoji: "👕",
    description: "100% cotton piqué, regular fit, ribbed collar, tipped placket with 2-button closure. Machine washable.",
    badge: "Best Seller",
    inStock: true
  },
  {
    id: 8,
    name: "Levi's 511 Slim Fit Jeans",
    brand: "Levi's",
    price: 2099,
    originalPrice: 3999,
    category: "fashion",
    rating: 4.5,
    reviews: 178000,
    emoji: "👖",
    description: "Sits below waist, slim from hip to ankle. 99% cotton + 1% elastane stretch denim. Classic 5-pocket styling.",
    badge: "",
    inStock: true
  },
  {
    id: 9,
    name: "Wildcraft Unisex Foldable Backpack 30L",
    brand: "Wildcraft",
    price: 1299,
    originalPrice: 2499,
    category: "fashion",
    rating: 4.2,
    reviews: 29400,
    emoji: "🎒",
    description: "Water-resistant 210D polyester, padded laptop sleeve (fits 15.6\"), 5 compartments, ergonomic shoulder straps.",
    badge: "New",
    inStock: true
  },
  {
    id: 10,
    name: "Fastrack Analog Men's Watch",
    brand: "Fastrack",
    price: 1295,
    originalPrice: 1995,
    category: "fashion",
    rating: 4.4,
    reviews: 61200,
    emoji: "🕐",
    description: "Stainless steel case, mineral glass, 30m water resistance, leather strap, Japanese quartz movement.",
    badge: "",
    inStock: true
  },

  // ── HOME & LIVING ────────────────────────────────────────
  {
    id: 11,
    name: "Prestige Iris 750W Mixer Grinder",
    brand: "Prestige",
    price: 2195,
    originalPrice: 3500,
    category: "home",
    rating: 4.4,
    reviews: 134000,
    emoji: "🍶",
    description: "3 stainless steel jars (0.4L, 0.8L, 1.5L), 3-speed control + pulse, motor overload protection, ISI approved.",
    badge: "Best Seller",
    inStock: true
  },
  {
    id: 12,
    name: "Milton Thermosteel Duo DLX Flask 1000ml",
    brand: "Milton",
    price: 699,
    originalPrice: 1195,
    category: "home",
    rating: 4.6,
    reviews: 392000,
    emoji: "🧴",
    description: "Double-wall insulation keeps hot 24hr / cold 48hr. Food-grade stainless steel, leak-proof lid.",
    badge: "Top Rated",
    inStock: true
  },
  {
    id: 13,
    name: "Philips 9W LED Bulb (Pack of 6)",
    brand: "Philips",
    price: 399,
    originalPrice: 599,
    category: "home",
    rating: 4.5,
    reviews: 287000,
    emoji: "💡",
    description: "9W replaces 60W incandescent, 900 lumens, cool daylight 6500K, 15,000hr lifespan, B22 base.",
    badge: "",
    inStock: true
  },
  {
    id: 14,
    name: "Solimo Non-Stick Cookware Set (3-Piece)",
    brand: "Amazon Solimo",
    price: 1099,
    originalPrice: 1899,
    category: "home",
    rating: 4.2,
    reviews: 56100,
    emoji: "🍳",
    description: "Includes 24cm tawa, 22cm kadhai, 20cm sauce pan. Granite finish coating, induction compatible, PFOA-free.",
    badge: "New",
    inStock: true
  },

  // ── SPORTS & FITNESS ────────────────────────────────────
  {
    id: 15,
    name: "Nivia Storm Running Shoes",
    brand: "Nivia",
    price: 1299,
    originalPrice: 2499,
    category: "sports",
    rating: 4.3,
    reviews: 38700,
    emoji: "👟",
    description: "EVA midsole with memory foam insole, mesh upper for breathability, anti-skid rubber outsole. Lightweight 280g.",
    badge: "Hot Deal",
    inStock: true
  },
  {
    id: 16,
    name: "Boldfit Resistance Bands Set (5 Bands)",
    brand: "Boldfit",
    price: 599,
    originalPrice: 1299,
    category: "sports",
    rating: 4.5,
    reviews: 72800,
    emoji: "🏋️",
    description: "5 resistance levels (2kg–25kg), natural latex, anti-snap technology, includes carry bag & workout guide.",
    badge: "Best Seller",
    inStock: true
  },
  {
    id: 17,
    name: "Strauss Anti-Skid Yoga Mat 6mm",
    brand: "Strauss",
    price: 799,
    originalPrice: 1499,
    category: "sports",
    rating: 4.4,
    reviews: 168000,
    emoji: "🧘",
    description: "6mm thick NBR foam, anti-slip texture both sides, moisture-resistant, includes carrying strap. 183×61cm.",
    badge: "",
    inStock: true
  },
  {
    id: 18,
    name: "Cosco Tourna Cricket Tennis Ball (Pack of 6)",
    brand: "Cosco",
    price: 349,
    originalPrice: 499,
    category: "sports",
    rating: 4.3,
    reviews: 23600,
    emoji: "🏏",
    description: "Rubber core with durable felt covering, ideal for practice and tape-ball cricket. Standard 5.5oz weight.",
    badge: "",
    inStock: true
  },
  {
    id: 19,
    name: "Decathlon Quechua 10L Hiking Backpack",
    brand: "Decathlon",
    price: 999,
    originalPrice: 1499,
    category: "sports",
    rating: 4.6,
    reviews: 47300,
    emoji: "🏕️",
    description: "100% recycled polyester, hydration-compatible (bladder sold separately), padded back panel, rain cover included.",
    badge: "Top Rated",
    inStock: true
  },
  {
    id: 20,
    name: "HealthSense Chef-Mate KS 33 Digital Kitchen Scale",
    brand: "HealthSense",
    price: 449,
    originalPrice: 799,
    category: "home",
    rating: 4.4,
    reviews: 89200,
    emoji: "⚖️",
    description: "Precision up to 1g, 5kg max capacity, tare function, stainless steel platform, unit conversion (g/kg/oz/lb).",
    badge: "",
    inStock: true
  }

];
